################### add users ############################
---
- hosts: local
  become: True
  become_method: sudo
  gather_facts: False
  
  tasks:
  - name: add user admin 
    user: name=admin state=present groups=sudo

  - name: add user pyapp
    user: name=pyapp state=present

################# install software #######################
- hosts: local
  become: True
  become_method: sudo
  gather_facts: False

  tasks:
  - name: ensure apt cache is up to date
    action: apt update_cache=yes
  - name: install required packages
    action: apt pkg="{{ item }}"
    with_items:
        - ssh
        - zip
        - unzip
        - tar
        - openssh-server
        - pwauth
        - build-essential
        - ipython
        - python
        - python-dev
        - python-pip
        - git
        - apache
        - libapache2-mod-security2
        - libapache2-mod-evasive
        - python2.5-psycopg2
        - postfix
        - wget
        - python-matplotlib
        - python-reportlab
        - mercurial
        - emacs
        - libapache2-mod-wsgi
        - postgresql
        - libpq-dev
        - python-psycopg2
        - unzip
        - fail2ban
        - python-pyOpenSSL

################ configure postgresql ################
- hosts: local
  become: yes
  become_method: sudo
  become_user: postgres
  gather_facts: False

  vars:
    dbname: pyapp
    dbpassword: '!$3curityPr0j3ct!' 

  tasks:
  - name: create database pyapp
    action: postgresql_db db=$dbname

  - name: ensure user pyapp has access to database
    action: postgresql_user db=$dbname user=pyapp password=$dbpassword priv=ALL

################# install web2py ###################
- hosts: local
  become: yes
  become_method: sudo
  gather_facts: False

  tasks:
  - name: pull web2py from github
    git:
      repo: https://github.com/web2py/web2py.git
      dest: /var/www/web2py
      update: yes
      force: yes

########### install Shadey Security Modules ########
  - name: checkout pyassetcontext code from github
    git:
      repo: https://github.com/ShadeySecurity/pyAssetContext.git
      dest: /var/www/web2py/applications/pyAssetContext
      accept_hostkey: yes
      ssh_opts: "-o StrictHostKeyChecking=no"
      force: yes

  - name: remove default welcome
    file: 
      path: /www/web2py/applications/welcome
      state: absent

  - name: Grab Shadey Security Home Portal Page Project from github
    git:
      repo: https://github.com/ShadeySecurity/PortalHome.git
      dest: /var/www/web2py/applications/welcome
      force: yes
      accept_hostkey: yes
      ssh_opts: "-o StrictHostKeyChecking=no"

########### Configure Web2py #############
  - name: change ownership of /var/www/web2py dir 
    file: 
      path: /var/www/web2py
      owner: www-data
      group: www-data
      mode: 0755
      recurse: yes
  - name: Apache Modules Setup
    apache2_module:
      state: present
      name: "{{ item }}"
    with_items:
      - ssl
      - proxy
      - proxy_http
      - headers
      - expires
      - wsgi
      - rewrite
      - security2
      - evasive
  - name: Apache Prod Enable
    lineinfile:
      path: /etc/apache2/apache2.conf
      regexp: "{{ item.regex }}"
      line: "{{ item.line }}"
    with_items:
      - { regex: "ServerSignature", line: "ServerSignature Off" }
      - { regex: "ServerTokens", line: "ServerTokens Prod" }

#### GENERATE KEYS FOR APACHE INTERUPTION ####
- hosts: local
  become: yes
  become_method: sudo
  become_user: www-data
  gather_facts: False
  tasks:
    - name: Generate Apache private SSL Key
      openssl_privatekey:
        force: False
        path: /etc/apache2/ssl/shadey_apache.pem
        size: 4096
        state: present
    - name: Generate Apache public SSL Key
      openssl_publickey:
        force: False
        path: /etc/apache2/ssl/shadey_apache.crt  
        privatekey_path: /etc/apache2/ssl/shadey_apache.pem
        state: present

### BAck to what we were doing ####
- hosts: local
  become: yes
  become_method: sudo
  gather_facts: False
  tasks:
    - name: disable default sites
      file:
        path: /etc/apache2/sites-enabled
        state: absent
        force: yes
    - name: re-create sites-enabled
      file:
        path: /etc/apache2/sites-enabled  
        owner: www-data
        group: www-data
        mode: 0755
    - name: copy our template file
      file:
        src: /var/www/web2py/applications/pyAssetContext/conf/default.conf
        dest: /etc/apache2/sites-available/default.conf
        owner: www-data
        group: www-data
        mode: 0555
        force: True
    - name: enable apache site
      command: "a2ensite default.conf"
    - name: PAM Me step1
      file:
        src: /etc/apache2/mods-available/authnz_external.load
        dest: /etc/apache2/mods-enabled
        state: link
        owner: www-data
        group: www-data
    - name: PAM Me step 2
      file: 
        src: /etc/pam.d/apache2
        dest: /etc/pam.d/httpd
        state: link
    - name: PAM user creation
      user:
        append: yes
        group: shadow
        name: www-data
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
  
## Finish up web2py setup
  - hosts: local
    become: yes
    become_method: sudo
    become_user: www-data
    gather_facts: False
    - name: Final Steps of Web2py
      shell:  |
        from gluon.widget import console; console();
        from gluon.main import save_password; save_password(raw_input('admin password: '),443)
      args:
        executable: /usr/bin/python
      
